# Generated by Django 5.1.7 on 2025-06-03 17:20

from django.db import migrations


def create_reminder_task(apps, schema_editor):
    IntervalSchedule = apps.get_model('django_celery_beat', 'IntervalSchedule')
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')

    schedule, _ = IntervalSchedule.objects.get_or_create(every=1, period='days')

    PeriodicTask.objects.get_or_create(
        interval=schedule,
        name='Send Reminders',
        task='apps.payments.tasks.send_payment_reminders',
    )

class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_alter_paymentplan_status'),
    ]

    operations = [
        migrations.RunPython(create_reminder_task),
    ]
